name: PHP MusicXML Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' # or '8.4snapshot' if not yet stable
          coverage: none

      - name: Run PHP MusicXML Script
        run: |
          php index.php

      - name: Upload generated files
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: |
            *.xml
            *.mid
            !*.php
